CREATE TABLE Refer(
    row_id varchar(20),
    col_id varchar(20),
    refer varchar(20),
    ke_ti varchar(200),
    ke_yi varchar(200)
);

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲子" , "寅", "寅巳申","伏吟，元胎","两贵差跌，六虎陈列，病讼皆畏，仕宦怡悦");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲子" , "丑", "子亥戌","比用，连茹","见生不生，互换无形，占父母病，不得安宁");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲子" , "子", "戌申午","比用，悖戾，斩关，励德","不待启齿，慨然而惠，昼卜如言，夜占仔细");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲子" , "亥", "午卯子","元首，三交，三奇，高盖，天烦","生空鬼存，破败家门，临难闭口，贵不施恩");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲子" , "戌", "戌午申","重审，斩关，炎上，狡童，泆女","支干互克，各被相触，昼畏中传，亡财失仆");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲子" , "酉", "寅酉辰","知一，长幼度厄","彼己遭孽，无德可说，惟忌交关，家道歇灭");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲子" , "申", "寅申寅","反吟，元胎，涉害","禄绝德废，以贵干贵，君子宜占，常人深畏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲子" , "未", "子巳戌","知一，铸印，乘轩，度厄","夜贵初害，事小凶大，行人未归，彼此驵侩");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲子" , "午", "辰申子","元首，润下，斩关，闭口，励德","昼虎遁鬼，传将俱水，既历灾危，然后美己");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲子" , "巳", "申亥寅","重审，元胎，苛察","止宜散虑，两贵皆怒，支干俱刑，家庭难住");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲子" , "辰", "辰午申","重审，不备，斩关，登三天，狡童","初财夹克，中午脱气，末乃虎鬼，惊危至矣");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲子" , "卯", "辰巳午","重审，进茹","解释忧疑，值此偏宜，求谋进取，寸步难移");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙丑" , "辰", "辰丑戌","伏吟，稼穑，斩关","木克九土，生阴生虎，伤食病胃，贪财祸阻");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙丑" , "卯", "子亥戌","重审，退茹，龙德，励德","彼此无礼，丁禄难倚，凡占凶甚，婚姻为美");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙丑" , "寅", "亥酉未","重审，间传，时遁","虎墓辛随，行人病归，名还魂格，迤逦生之");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙丑" , "丑", "丑戌未","稼穑，赘婿，励德，游子，三丘，五墓","循环周布，昼夜辛墓，处此危疑，自来相顾");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙丑" , "子", "巳丑酉","从革，乙奇","外勾里连，虽被熬煎，众金生水，昼贵同全");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙丑" , "亥", "卯戌巳","知一，斫轮，四绝，察微","生虚鬼实，仕宦占吉，夜因神愿，禄动危失");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙丑" , "戌", "戌辰戌","反吟，稼穑，斩关，关格","日墓临支，宅有伏尸，三传俱陷，妻丧财遗");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙丑" , "酉", "寅未子","重审，励德，天狱","凶里藏利，迤逦而至，昼传夹克，寅全死气");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙丑" , "申", "酉丑巳","重审，狡童，从革","俗庶难任，病讼俱兴，守官宜卜，俸倍职升");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙丑" , "未", "未戌丑","重审，斩关，富贵，丘墓，阴不备","支干乘墓，如处云雾，磨罗而归，妻财共聚");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙丑" , "午", "申戌子","重审，间传，龙德，涉三渊","脱空昼迎，禄作元丁，干官贵怒，凶吉无成");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙丑" , "巳", "寅卯辰","元首，进茹，罗网，夹定格","支干拱传，惟喜春占，疑凶凶有，向后灾潜");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙寅" , "巳", "巳申寅","伏吟，元胎，自任，临官，励德","干传入支，行人远归，禄财生聚，所卜皆宜");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙寅" , "辰", "子亥戌","知一，斩关，退茹，天网","畏空官鬼，病防再至，子丑夜常，牛女合位");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙寅" , "卯", "丑亥酉","重审，间传，龙战，隔角","虽生难恃，子卯无礼，反为败神，切休恋贵");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙寅" , "寅", "亥巳申","蒿矢，元胎，龙德，不备","执弓忘矢，事声迤逦，舍此危疑，彼来生己");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙寅" , "丑", "戌午寅","重审，炎上，斩关，狡童","自墓传生，先迷后醒，全无和气，上刑下刑");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙寅" , "子", "子未寅","知一，四绝，度厄","彼己灾殄，三传外战，干支坐墓，事终难辨");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙寅" , "亥", "寅申寅","无依，元胎，比用，察微","交互虽密，合之却益，德禄鬼财，并无实迹");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙寅" , "戌", "子巳戌","比用，乘轩，铸印，察微","两蛇夹墓，家遭咒诅，熟视三传，略无好处");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙寅" , "酉", "酉丑巳","重审，从革，地网，龙德","守死赔钱，夜将助焉，所得一贯，家费万千");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙寅" , "申", "申亥寅","重审，进退，不备","递相荐引，夜无凭准，屈尊就卑，所谋和允");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙寅" , "未", "辰午申","重审，间传，斩关，励德","壬申乘马，见财难舍，得来何用，添修屋瓦");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙寅" , "午", "辰巳午","重审，进茹，六化，龃龉","第四课用，末与日共，格号朝元，百发百中");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁卯" , "未", "卯子午","伏吟，三交，龙战，奇化","三重卯丁，子水居中，动用非细，鬼贼须逢");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁卯" , "午", "丑子亥","重审，退茹，夜衰，三奇","禄在虎旁，勿恋寅乡，食一粒粟，失半年粮");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁卯" , "巳", "亥酉未","涉害，间传，察微，极阴","传课俱阴，事转沉沦，递相脱赚，勿依贵人");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁卯" , "辰", "子酉午","遥克，二烦，天网，三交","禄乘元虎，重遭鬼苦，中间闭口，尚忧门户");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁卯" , "卯", "未卯亥","元首，曲直，四墓，复生，不备","传课循环，事在关栏，木局休恃，昼将宜看");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁卯" , "寅", "戌巳子","重审，地网，天狱，传墓","干上长生，守则无穷，动逢鬼墓，命忌巳宫");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁卯" , "丑", "卯丑卯","反吟，三交，二烦，斫轮","满地皆丁，岂容少停，夏昼火厄，贵财夜迎");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁卯" , "子", "巳戌卯","重审，铸印，乘轩","彼己皆凶，空墓居中；末丁初马，事无定踪");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁卯" , "亥", "未亥卯","重审，曲直，不备，回环","昼将脱丁，传却生身，好恶中半，遁循贵嗔");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁卯" , "戌", "酉子卯","重审，三交，六仪，地烦","交车眷恋，递相推荐，自己昏迷，权摄可羡");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁卯" , "酉", "酉亥丑","重审，间传，励德，龙战","昼夜贵聚，事无凭据，本身力弱，占病深虑");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁卯" , "申", "辰巳午","见机，顺茹，斩关，龙战","夜占财退，必因同类，病者腰疼，昼贵勿恃");


INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊辰" , "巳", "巳申寅","伏吟，天罗，斩关，泆女，元胎","昼虎乘生，夜龙鬼并，机关在末，能败能成");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊辰" , "辰", "卯寅丑","比用，退茹，不备，天罡","鬼临干墓，宜求门户，冬昼火灾，病讼如缕");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊辰" , "卯", "丑亥酉","重审，间传，极阴，龙德","彼己受克，丁马身宅，夜传皆陷，静躁无益");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊辰" , "寅", "寅亥申","元首，奇化，元胎，地结","守之见伤，动入空乡，昼虎祛祸，夜龙辅戕");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊辰" , "丑", "子申辰","重审，润下，旬化","上和下睦，传财盛极，春夏可取，秋冬难得");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊辰" , "子", "子未寅","缀瑕，四绝，度厄","夜贵日蹬，虎鬼骖乘，正月妻胎，七月损孕");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊辰" , "亥", "巳亥巳","反吟，元胎，见机，斩关","课传俱空，行住无踪，我去彼绝，久病须凶");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊辰" , "戌", "寅卯子","重审，斩关，天罗，飞魂","鬼虽潜伏，唯嫌夜卜，三传窝犯，利害相逐");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊辰" , "酉", "子辰申","弹射，润下，斩关，励德","交车作合，彼此相脱，已往之财，天助可夺");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊辰" , "申", "亥寅巳","弹射，元胎，孤寡","财马官鬼，皆不相干，执弓忘弹，坐守为欢");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊辰" , "未", "申戌子","重审，间传，泆女，涉三渊","初生末财，两事俱乖，子遁虎鬼，金鬼火煨");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊辰" , "午", "寅午午","别责，不备，进退","用鬼传刃，舍益就损，屈尊居卑，甘受偃蹇");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己巳" , "未", "巳申寅","伏吟，自任，元胎","德印长生，君子利亨，迤逦克伐，寅为祸萌");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己巳" , "午", "卯寅丑","元首，连茹，斩关，三奇，不备","旺禄临身，动作遭刑，君子宜卜，遁乙丙丁");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己巳" , "巳", "丑亥酉","重审，间传，极阴，不备","支乘幸焉，枉历三传，乙丑夜虎，破败忘钱");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己巳" , "辰", "寅亥申","蒿矢，元胎，斩关，励德","夜传俱空，万事无踪，勿欺蒿矢，委镞有功");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己巳" , "卯", "卯亥未","元首，曲直，泆女，天网","卯乘合虎，与贼为伍，虽有催官，常人被苦");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己巳" , "寅", "酉辰亥","涉害，无禄，伏殃","课名无禄，干支不睦，破败墓建，空财后逐");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己巳" , "丑", "巳亥巳","反吟，无依，元胎，重审，孤寡","生乘虎来，频失财钱，所谋无实，陷没三传");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己巳" , "子", "巳戌卯","知一，铸印，斩关，乘轩，励德","循环无已，鬼助生气，铸印乘轩，常占生畏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己巳" , "亥", "酉丑巳","涉害，从革，察微，泆女","传生空亥，索还魂债，昼贵加贵，夜贵深怪");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己巳" , "戌", "申亥寅","重审，元胎，斩关，励德","长生财德，三事无力，昼夜推之，两贵蹉跌");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己巳" , "酉", "亥丑卯","间传，弹射，不备，寡宿，进退","弹射亡丸，勿干贵官，降志求生，夜丑须看");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己巳" , "申", "申申午","昴星，龙德，天罗，虎视，掩目","辰之阴神，及夫课名，三传并见，五虎纵横");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚午" , "申", "申寅巳","伏吟，元胎，自任","昼德乘虎，中财休取，献纳尤宜，不利商贾");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚午" , "未", "午巳辰","遥克，逆茹，蒿矢","交关且尔，可疑蒿矢，蛇雀空逢，五火焚毁");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚午" , "午", "午辰寅","元首，间传，顾祖，回环","幸名顾祖，亡门欺侮，可恨者寅，暗助初午");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚午" , "巳", "巳寅亥","元首，元胎","昼生夜克，讼凶官吉，亥喻萧何，贵不悯恤");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚午" , "辰", "戌子寅","知一，炎上，斩关","自来生身，切勿信凭，倘遇夜卜，总是幽冥");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚午" , "卯", "戌巳子","比用，龙战，官爵","长生虽在，全无倚赖，丑为干墓，卯作支败");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚午" , "寅", "寅申寅","反吟，涉害，元胎","财虽可绝，七虎排列，切勿取财，秋占焚燕");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚午" , "丑", "辰酉寅","比用，用墓，闭口","生旺财气，三传皆值，夜元雀虎，未财衰替");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚午" , "子", "辰申子","涉害，润下，闭口，励德，斩关","脱干伤支，占失无疑，人身多病，宅渐崩颓");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚午" , "亥", "酉子卯","重审，高盖，三交，伏殃，二烦","财内藏丁，无礼相刑，必然凶动，休倚贵屏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚午" , "戌", "申戌子","涉害，间传，乱首，斩关，魄化，芜淫，涉三渊，飞魄","中末空坠，自招其祸，事绪萦纡，病者难可");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚午" , "酉", "戌未酉","昴星","失系来情，未免虚惊，无中生有，然后安宁");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛未" , "戌", "未丑戌","伏吟，稼穑，斩关，游子","自宅传人，彼求我身，守之上等，动则遭迍");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛未" , "酉", "巳辰卯","蒿矢，退茹，天罡","闭口难言，遂往投传，化为全火，以致凶迁");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛未" , "申", "午辰寅","元首，顾祖，龙德，死奇","巳午两火，并来为祸，取末寅财，其灾难躲");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛未" , "未", "亥未未","别责，芜淫，不备","支生我躬，去寻脱空，惭赧而回，快乐无穷");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛未" , "午", "卯亥未","知一，曲直，伏殃，狡童","午丁双见，先恶后善，携财祷贵，庶免灾殄");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛未" , "巳", "酉辰亥","涉害，无禄，四绝","无禄可守，禄又闭口，君子恶之，彼已有咎");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛未" , "辰", "巳丑辰","反吟，无依，天网，井栏关","意孟来求，奈何互墓，甘分沉沦，两贵皆怒");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛未" , "卯", "巳戌卯","涉害，铸印，乘轩，励德，度厄","上刑下刑，昼失娉婷，本无和气，况有旬丁");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛未" , "寅", "亥卯未","知一，曲直，寡宿","昼财失散，动多灾难，夜贵纯财，外徒好看");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛未" , "丑", "亥丑丑","别责，励德，芜淫，不备","昼乘虎墓，弃迎贼伍，留宿仍前，俯就免苦");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛未" , "子", "寅辰午","弹射，出阴","夜禄虎守，却宜闭口，倘居窘乡，释然无咎");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛未" , "亥", "申亥申","昴星，天罗，掩目","五虎昼逢，殃祸重重，全作六害，夜稍从容");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬申" , "亥", "亥申寅","伏吟，自任，元胎，寡宿，杜传","昼德禄空，脱马未逢，长生乘武，守动勿容");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬申" , "戌", "戌酉申","元首，退茹，斩关，朝支","先鬼后空，退则有功，凡谋勉力，关格须逢");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬申" , "酉", "午辰寅","元首，顾祖，间传，泆女","宅败人衰，末助初财，阴入夜遁，七月怀胎");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬申" , "申", "巳寅亥","元首，病胎，不备，自在","坐谋有益，动用费力，元虎临身，稍有忧惕");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬申" , "未", "子申辰","重审，润下，励德，斩关，狡童，六仪","所谋驵诈，妻财最怕，夜贵在日，昼贵居夜");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬申" , "午", "午丑申","涉害，度厄，四绝","午被挤排，夜损妻财，惟妨长上，手足防灾");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬申" , "巳", "寅申寅","反吟，无依，知一，励德，元胎","交居先绝，前脱后脱，元合昼逢，两贵不悦");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬申" , "辰", "辰酉寅","元首，斩关，天罡","墓干墓支，人晦宅晦，动则灾危，三传不美");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬申" , "卯", "未亥卯","重审，曲直","刑害无礼，脱空后至，夜将赖传，昼占弛废");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬申" , "寅", "巳申亥","弹射，不备，元胎","昼占必失，家道寂寞，惟宜俯就，两贵无力");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬申" , "丑", "子寅辰","重审，间传，向阳","两贵共处，病笃可愈，以凶制凶，蛇冲虎去");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬申" , "子", "丑寅卯","元首，连茹，三奇，天网","守之则旺，动遭刃网，牛女宜婚，喜事怅怏");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸酉" , "丑", "丑戌未","伏吟，自信，天罡，励德，稼穑，三奇","支干互生，华盖伤刑，昼夜占病，先重后轻");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸酉" , "子", "未午巳","蒿矢，退茹","守禄为良，动被传伤，勿欺蒿矢，昼镞坚刚");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸酉" , "亥", "未巳卯","蒿矢，回明，间传","干传无用，射物难中，昼若占之，苏宽病讼");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸酉" , "戌", "午卯子","涉害，轩盖，三交，二烦","全伤身宅，戌空午实，元后夺财，彼凶己吉");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸酉" , "酉", "巳酉丑","元首，从革，不备，回还","昼将生金，传金育身，回还曲折，皆藉众人");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸酉" , "申", "卯戌巳","见机，四绝，斫轮","两贵拱宅，昼传虎戌，熟视兔蛇，夜不安逸");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸酉" , "未", "卯酉卯","无依，三交，龙战，励德","三传身宅，夜将相克，满目旬丁，门户动慝");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸酉" , "午", "未子巳","知一，度厄，迍福","财官德禄，俱受其克，前后引从，足可解厄");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸酉" , "巳", "酉丑巳","涉害，从革，不备，盘珠","贵财心术，俯就岂逸，昼将生传，传金生日");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸酉" , "辰", "辰未戌","元首，稼穑，斩关","交互徒然，夜禄乘元，弃而孟动，众土为愆");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸酉" , "卯", "丑卯巳","元首，间传，出产","昼贵夜聚，无屋可住，彼己怀脱，虚鬼空布");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸酉" , "寅", "亥子丑","重审，进茹，孤寡","三传拱定，行人归近，事不出家，贼在彼隐");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲戌" , "寅", "寅巳申","伏吟，元胎，斩关","马载虎鬼，昼占可畏，幸而值空，夜财失费");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲戌" , "丑", "子亥戌","知一，退茹","奇仪既夹，常人难压，君子宜占，试登高甲");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲戌" , "子", "午辰申","涉害，见机，间传，励德，顾祖","六位全阳，常人散殃，马载虎鬼，催人勿遑");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲戌" , "亥", "巳申寅","遥克，蒿矢，元胎","矢箭来伤，幸尔空亡，居家闭口，生计荣昌");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲戌" , "戌", "寅午戌","重审，炎上，赘婿，斩关","内外勾连，宅盛人愆，亡财后至，奴婢防奸");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲戌" , "酉", "子未寅","知一，四绝","初末拱贵，尊上偏喜，空鬼虚惊，互乘脱气");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲戌" , "申", "寅申寅","反吟，元胎，斩关","夜禄虎雄，鬼却乘龙，细详好恶，来去俱空");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲戌" , "未", "子巳戌","知一","夜贵作墓，讼庭官怒，解纷恃戌，枉者可错");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲戌" , "午", "寅午戌","元首，炎上，励德，泆女，不备","劳心取财，宅广人灾，宜乎作赘，耗盗萦回");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲戌" , "巳", "申亥寅","重审，元胎","生鬼皆空，禄被虎攻，宅逢丁马，动意尤浓");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲戌" , "辰", "辰午申","涉害，斩关，间传，泆女，登三天","昼虎空亡，临危弗殃，财乘遁鬼，申命全伤");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲戌" , "卯", "辰巳午","知一，进茹","昼传盗休，赖尔亥水，末助初财，交居和美");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙亥" , "辰", "辰亥巳","伏吟，自任，斩关","支夜三武，三勾可虑，末马遁辛，特来相苦");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙亥" , "卯", "戌酉申","元首，斩关，励德，闭口","退入鬼藩，幸而空焉，病防再至，煞号销魂");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙亥" , "寅", "酉未巳","遥克，蒿矢，泆女，寡宿","交车虽美，所畏蒿矢，熟视初传，全无威势");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙亥" , "丑", "丑戌未","重审，稼穑，芜淫，励德","递互克伐，不相顾接，财化为鬼，求贵事捷");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙亥" , "子", "未卯亥","涉害，曲直，泆女","自墓传生，先迷后醒，昼占家宅，昏晦伶仃");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙亥" , "亥", "午丑申","重审，不备","中丁初脱，空鬼居末，幸遇支生，死而后活");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙亥" , "戌", "巳亥巳","反吟，元胎","昼将凶恶，须防有失，动则双双，费用不值");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙亥" , "酉", "寅未子","重审，斩关，不备，励德","空鬼干遇，支乘实墓，用鬼获财，迤逦克去");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙亥" , "申", "未亥卯","重审，曲直，泆女，丧门","官贵无补，夜禄乘虎，宅虽旺临，昼乘元武");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙亥" , "未", "未戌丑","重审，稼穑，飞魂，游子","钱财遍地，得不偿费，两贵俱空，虎丁可畏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙亥" , "午", "申戌子","重审，间传，涉三渊，寡宿","虎人朱雀，讼极凶恶，不论空亡，贵难倚托");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙亥" , "巳", "丑寅卯","元首，连茹，三奇","拱虚一位，所欠财利，木命属龙，方始遂意");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙子" , "巳", "巳申寅","伏吟，自任，元胎","禄财错综，昼空无用，寅马为生，夜虎凶动");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙子" , "辰", "戌酉申","知一，退茹，斩关，六仪，泆女","病死墓绝，彼此不悦，病讼再兴，财如鬼夺");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙子" , "卯", "丑亥酉","重审，斩关，极阴，三奇","身败瘦瘠，墓神克宅，乘旬丁旺，旧财可得");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙子" , "寅", "午卯子","元首，三交，二烦，轩盖","马载长生，酉财难侵，夜元昼虎，占婢逃淫");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙子" , "丑", "申辰子","弹射，润下，闭口，泆女","交居匪吉，昼占财失，三合六合，占官必陟");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙子" , "子", "子未寅","涉害，四绝，不备，乱首","课传上克，乱首丧德，采葛寻脑，妻财作慝");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙子" , "亥", "午子午","反吟，知一，无依，三交","德禄旺刃，并皆灰烬，到处去来，难退难进");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙子" , "戌", "巳戌卯","重审，铸印，不备","自取其祸，课传相锁，两蛇加墓，德禄何可");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙子" , "酉", "酉丑巳","重审，从革，斩关，伏殃","三传无迹，两贵坐厄，夜将生之，财亡再获");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙子" , "申", "申亥寅","重审，元胎，寡宿","己财先费，众人怀惠，倘若夜占，一事无济");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙子" , "未", "辰午申","重审，间传，励德，登三天","交互六害，各怀驵侩，传脱刃空，全无倚赖");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙子" , "午", "寅卯辰","知一，进茹，蓦越","支干拱簇，所虚者禄，夜贵作空，昼贵履狱");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁丑" , "未", "丑戌未","自信，稼穑，游子，三奇","身动则徙，彼投于己，两丁拱墓，静中动矣");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁丑" , "午", "子亥戌","重审，退茹","昼禄虎边，遂谒三传，随鬼归墓，终受淹缠");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁丑" , "巳", "亥酉未","重审，间传，时遁","遍地贵人，利见大人，支干互绝，六位阴纯");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁丑" , "辰", "子辰戌","遍地贵人，利见大人，支干互绝，六位阴纯","递相暗昧，各甘其晦，魁罡乘丁，如骑虎背");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁丑" , "卯", "巳丑酉","元首，从革","小利先施，大财必归，传空将土，重重取妻");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁丑" , "寅", "卯戌巳","重审，四绝，斫轮","木坐空申，斫朽木轮，事虽败坏，再造出旬");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁丑" , "丑", "亥未丑","反吟，无亲，并栏射","动意先有，主客相就，契义难忘，欢欣如旧");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁丑" , "子", "巳戌卯","重审，铸印，乘轩","彼此不足，然后和睦，虽尔貌恭，终赖其仆");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁丑" , "亥", "酉丑巳","重审，从革，蓦越","传生亥鬼，夜将无畏，两贵虽伤，空财生起");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁丑" , "戌", "午戌辰","昴星，掩目，虎视","干支乘墓，昼占蛇虎，两贵皆空，略无少补");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁丑" , "酉", "酉亥丑","重审，间传，凝阴，孤寡","身临空死，求财不喜，丁马俱逢，两贵徒尔");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁丑" , "申", "申酉戌","重审，进茹，流金","守之乏财，进步陷没，墓神助财，折本再发");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊寅" , "巳", "巳申寅","伏吟，自任，元胎","连名状论，台阁上言，我求于彼，顺受和焉");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊寅" , "辰", "子亥戌","知一，退茹，斩关，重阴，三奇","三奇六仪，凡谋可施，稍嫌幽暗，斩关昼驰");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊寅" , "卯", "丑亥酉","重审，间传，极阴，三奇，龙战，励德","我就他侮，他中我计，天道好还，子卯狠戾");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊寅" , "寅", "寅亥申","元首，元胎，不备，乱首","两位空申，岂胜四寅，守动皆祸，昼夜贵嗔");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊寅" , "丑", "戌午寅","重审，炎上，泆女，斩关","虎鬼夜潜，斩关昼占，我旺彼败，屋破人添");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊寅" , "子", "子未寅","重审，四绝","交互逢败，夏夜火怪，鬼虽是寅，熟视何碍");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊寅" , "亥", "寅申寅","无依，元胎，度厄","彼此合忌，交淡如水，生克既无，如斯而已");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊寅" , "戌", "子巳戌","知一，斩关，铸印，蓦越","禄神及德，戌墓子克，夜贵闭口，作墓临宅");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊寅" , "酉", "丑午酉","昴星，虎视，三光，转蓬，励德","首末皆空，刃虎居中，两贵勿恃，终守困穷");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊寅" , "申", "申亥寅","重审，元胎，不备","虚生天干，中传财散，祸乃自招，夜鬼凶悍");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊寅" , "未", "辰午申","重审，间传，斩关，登三天，狡童","自墓传生，终不能宁，递相挽抑，两贵皆丁");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊寅" , "午", "辰巳午","重审，进茹","身宅罗网，守之自旺，动作他谋，许多恶况");


INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己卯" , "未", "卯子午","伏吟，自信，三交","卯鬼交逢，昼合夜龙，随时闭口，灾祸犹攻");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己卯" , "午", "丑子亥","重审，退茹，三奇，励德，蓦越","遁传三奇，所卜皆宜，动用既可，退守无亏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己卯" , "巳", "亥酉未","涉害，间传，极阴，九丑，龙战","身马宅丁，不容少停，元脱空败，阴极阳生");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己卯" , "辰", "子酉午","弹射，三交，励德，二烦","守辰厄塞，动值遥克，中末皆空，解忧释惑");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己卯" , "卯", "未卯亥","涉害，曲直，泆女，不备，魄化，飞魂","上门见制，循环不已，昼贵休干，夜亦如是");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己卯" , "寅", "戌巳子","重审　斩关","生气居中，子戌不容，身边官鬼，于火有功");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己卯" , "丑", "卯酉卯","反吟，无依，三交，九丑","俱鬼俱空，见凶不凶，夜忧酉鬼，火怪虚逢");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己卯" , "子", "巳戌卯","知一，铸印，乘轩，励德","身宅俱贵，夜费昼惠，末来助初，卯鬼无畏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己卯" , "亥", "未亥卯","涉害，比用，曲直，乱首，不备","灾祸难遏，夜虎居末，自招其咎，何由免脱");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己卯" , "戌", "酉子卯","重审，三交，蓦越","交车颇美，脱空初值，元卯末逢，穿窬防备");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己卯" , "酉", "亥丑卯","遥克，弹射，间传，纯阴，溟蒙","弓在弹亡，夜失须防，六阴全备，两贵渺");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己卯" , "申", "辰巳午","重审，进茹，斩关","虚贵干遇，宅乘日墓，拱三欠一，惟禄难顾");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚辰" , "申", "申寅巳","伏吟，自任，元胎","空禄宜舍，去乘财马，官鬼长生，须分真假");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚辰" , "未", "卯寅丑","元首，退茹，联芳","始贪货财，丁马随来，详分昼夜，冬雀火灾");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚辰" , "午", "寅子戌","涉害，见机，间传，顾祖","彼此不和，寅来教唆，尊求卑下，莫被财魔");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚辰" , "巳", "巳寅亥","元首，元胎","夜巳鬼名，昼巳长生，亥分生克，能败能成");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚辰" , "辰", "子申辰","重审，润下，不备，斩关","彼求于己，似乎不美，事到周全，致成迤逦");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚辰" , "卯", "午丑申","涉害，绝嗣，蓦越","四课犯上，祭祀绝享，中丑遁丁，动之灾障");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚辰" , "寅", "寅申寅","反吟，无依，元胎","动意虽切，满目空绝，夜逢五虎，惊不可说");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚辰" , "丑", "寅未子","重审，蓦越，引从","己财先费，方获厚利，初引末从，旬丁昼贵");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚辰" , "子", "辰申子","元首，润下，不备，励德，闭口","课传循环，脱空在关，无心俯就，两贵难扳");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚辰" , "亥", "寅巳申","弹射，元胎","夜贵闭口，马负财走，幸而逢生，空亡随后");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚辰" , "戌", "申戌子","涉害，间传，斩关，涉三渊","初中泛浮，两虎堪忧，乘生坐克，乐里成愁");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚辰" , "酉", "午未申","蒿矢，进茹，丽明","支干交会，拱贵在内，蒿矢带金，申空无畏");


INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛巳" , "戌", "巳申寅", "伏吟，元胎，斩关","旅情未已，半路而止，凡事折腰，遇中有滞");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛巳" , "酉", "卯寅丑","元首，退茹，斩关，励德","人足乘丁，岂容少停，斩关月将，万里行程");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛巳" , "申", "丑亥酉","间传，极阴","申夜空空，墓脱须逢，家须富有，丁马逢凶");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛巳" , "未", "寅亥申","遥克，弹射，元胎","彼己可守，贵临户牖，昼虎脱马，夜虎闭口");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛巳" , "午", "午寅戌","元首，炎上","将土传火，常人免祸，君子宜占，宅丁倾堕");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛巳" , "巳", "未寅酉","涉害，无禄，不备，乱首","课传上克，名为无禄，彼此皆怕，就门溷渎");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛巳" , "辰", "巳亥巳","反吟，无依","长生莫举，就辰浊土，失十得一，勿登贵堵");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛巳" , "卯", "卯申丑","重审，斩关，励德，不备，斫轮，乱首","课同斫轮，昼虎遁丁，自取乱首，凶动难停");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛巳" , "寅", "酉丑巳","知一，从革，狡童","昼虎丁丑，凶祸必有，禄空破碎，居家难守");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛巳" , "丑", "申亥寅","重审，元胎","虎墓值丁，暗祸来侵，宅中败走，夜贵真诚");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛巳" , "子", "寅辰午","遥克，弹射，出三阳，间传","弹射助鬼，赖有子水，未土不甘，财寅可委");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛巳" , "亥", "午未申","遥克，蒿矢，进茹","蒿矢带金，射中伤身，虚惊定有，守默因循");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬午" , "亥", "亥午子","伏吟，自任，杜传","禄上空常，财禄可伤，倘若他逐，暗伤不睦");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬午" , "戌", "戌酉申","元首，退茹，六仪，斩关","关隔频频，虎戌临身，退求生意，空亡后蹲");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬午" , "酉", "寅子戌","元首，斩关，间传","阳拱阳神，两贵为邻，辰酉合定，酒色败身");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬午" , "申", "巳寅亥","元首，元胎","虚生难靠，往临脱耗，天将宜详，旦贵勿告");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬午" , "未", "戌午寅","重审，六仪，炎上，励德","交互传合，递互相脱，财化成鬼，凶化难遏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬午" , "午", "午丑申","重审，不备，赘婿","支财就日，夜元空失，熟视其中，占尊不吉");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬午" , "巳", "午子午","反吟，比用，三交，度厄，励德","三财被贼，二贵受克，昼旺虎临，左右不得");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬午" , "辰", "辰酉寅","知一，斩关，不备","彼己俱伤，卑下不甘，未免一动，盗失多端");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬午" , "卯", "未亥卯","重审，曲直，斩关","人少宅宽，虽费成欢，三传俱脱，逃避尤安");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬午" , "寅", "酉子卯","重审，三交，二烦，寡宿","交互生意，终是不美，昼号三交，夜乃损己");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬午" , "丑", "申戌子","重审，间传，励德，九丑","丁与壬午，求谒为良，虎入朱雀，遇殃不殃");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬午" , "子", "丑寅卯","元首，进茹，芜淫，三奇","交互凌虐，盗脱不祥，刃乘元虎，脱虚相伤");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸未" , "丑", "丑戌未","伏吟，自任","四丁分布，勾入火库，侥幸得财，切勿再顾");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸未" , "子", "巳辰卯","弹射，退茹，蓦越","支干上下，各自和畅，巳火丙雀，俱财可向");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸未" , "亥", "巳卯丑","弹射，间传，解离","课传五阴，贵不一心，朱丁初马，动获赀金");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸未" , "戌", "戌未辰","元首，斩关，稼穑，游子","自干归家，我求于他，满地鬼贼，闭口为嘉");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸未" , "酉", "卯亥未","涉害，从革，励德","三传育身，昼将生金，有官有印，俗庶难胜");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸未" , "申", "卯戌巳","重审，斫轮，罗网，励德","虚生实盗，贵多难告，朽木难雕，妻财怎靠");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸未" , "未", "未丑未","反吟，稼穑，乱首，游子","俱丁俱鬼，加临不美，暗以财交，讼论遂止");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸未" , "午", "巳戌卯","知一，铸印，度厄","彼己唇吻，相交和顺，末助初财，宜讲秦晋");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸未" , "巳", "酉丑巳","涉害，从革","人丰宅堕，我福他祸，昼将生传，传金生我");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸未" , "辰", "辰未戌","元首，斩关，稼穑","众情皆恶，宜自相度，闭口居中，免被凌虐");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸未" , "卯", "巳未酉","遥克，弹射，励德，间传","传及支干，总下生上，销根断源，凡谋恶况");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸未" , "寅", "申寅申","昴星，掩目","元盗昼乘，满目空神，守弃不可，身若浮萍");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲申" , "寅", "寅巳申","伏吟，自任，元胎","行人到户，来必欺侮，昼禄遁庚，末逢众虎");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲申" , "丑", "子亥戌","知一，退茹，重阴","递相蒙蔽，两贵恃势，生计虽荣，子息废弃");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲申" , "子", "午辰寅","涉害，间传，顾祖，励德","宅内脱空，嗣息飘蓬，庚赖此制，然后尊崇");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲申" , "亥", "巳寅亥","元首，元胎","自支传干，彼来相向，丁马交横，闭口为上");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲申" , "戌", "子申辰","涉害，炎上，狡童，斩关","魁罡并临，中末空沉，若当寅月，虎马庚侵");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲申" , "酉", "戌巳子","知一，罗网，铸印","交互乘旺，各临墓上，动遭罗网，中传懊丧");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲申" , "申", "寅申寅","反吟，元胎，乱首","缘不自尊，凶犹可言，若逢夜卜，八虎攒吞");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲申" , "未", "子巳戌","比用，铸印","干支墓临，夜讼难胜，人渐通泰，宅渐隆兴");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲申" , "午", "辰申子","元首，润下，励德，闭口，蓦越","人盛宅隘，我成他败，干上脱空，三传可解");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲申" , "巳", "申亥寅","重审，元胎","冲克生扶，贵怒畏初，马载夜虎，非细驰驱");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲申" , "辰", "辰午申","涉害，斩关，间传，登天","支干魁罡，中末空亡，移远就近，岁月时详");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲申" , "卯", "辰巳午","重审，进茹，罗网，升阶","人宅皆旺，动遭罗网，夜占脱甚，互坐墓上");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙酉" , "辰", "辰酉卯","干上辰","伏吟，自信，斩关，杜传");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙酉" , "卯", "申未午","遥克，蒿矢，退茹","辛申并至，常人可畏，身宅皆凶，君子斯贵");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙酉" , "寅", "未巳卯","弹射，间传，回明","昼虎墓身，勿近财婚，取之有咎，讼枉难伸");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙酉" , "丑", "丑戌未","重审，稼穑，九丑","面前相害，私里眷爱，若论财交，彼明己昧");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙酉" , "子", "巳丑酉","元首，从革","满盘皆鬼，来生子水，宜远求财，忧变成喜");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙酉" , "亥", "亥午丑","知一，不备，四绝","亥水乘丁，奔入庭宅，舍益就损，空脱交并");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙酉" , "戌", "卯酉卯","反吟，无依，龙战","三辛临卯，所谋被恼，夜逢蛇虎，禄难求饱");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙酉" , "酉", "未子巳","知一，不备，乱首，蓦越","三传空盗，切勿倨傲，上门欺凌，以德为报");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙酉" , "申", "申子辰","三传空盗，切勿倨傲，上门欺凌，以德为报","人盛宅狭，贵多不惬，将土传水，财印相接");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙酉" , "未", "未戌丑","重审，稼穑","两未墓乙，赖众悯恤，子害戌刑，丑冲渐吉");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙酉" , "午", "申戌子","重审，间传，涉三渊","空脱临身，宅乘马丁，贵来官显，福佑财亨");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙酉" , "巳", "亥子丑","重审，进茹，龙潜","面前被盗，前路可造，因动逢生，庶免空耗");


INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙戌" , "巳", "巳申寅","伏吟，斩关，元胎","财禄长生，传内俱逢，居家昏暗，闭口不宁");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙戌" , "辰", "卯寅丑","元首，退茹，斩关","退入生乡，进之亦强，壬辰在上，守之见殃");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙戌" , "卯", "丑亥酉","重审，间传","交车六合，我丰彼乏，二贵相投，事恐废业");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙戌" , "寅", "亥申巳","蒿矢，元胎","昼贵蒿矢，告之委靡，生气临身，宅中自毁");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙戌" , "丑", "酉巳丑","弹射，从革","将助财业，尽得尽失，纵取归家，如汤沃雪");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙戌" , "子", "子未寅","知一，四绝，不备","并来克身，甘分昏沉，禄既闭口，病托食歆");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙戌" , "亥", "巳亥巳","反吟，元胎，斩关","三传闭口，壬虎夜走，进退俱难，人伤宅朽");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙戌" , "戌", "申丑午","知一，斩关，不备","两蛇夹墓；抱石而渡，采葛寻根，申加卯故");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙戌" , "酉", "酉丑巳","重审，从革","夜将助财，唯长上灾，虎元加寅，全去其财");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙戌" , "申", "申亥寅","重审，元胎","亥临财气，反被财制，迤逦育身，丁马交位");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙戌" , "未", "子寅辰","重审，间传","空脱临身，仇如家人，墓呼病者，虎载壬辰");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙戌" , "午", "亥子丑","重审，三奇，进茹","昼贵入宅，结绝凶逆，旺气虽临，熟视何益");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁亥" , "未", "亥未丑","伏吟，杜传","身宅皆丁，岂容少停，递相吞啖，惊怪交并");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁亥" , "午", "戌酉申","元首，退茹，斩关","昼虎乘禄，初戌墓宅，弃此得财，死病为厄");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁亥" , "巳", "酉未巳","弹射，间传","用遥传陷，自支归干，破碎临支，钱财不完");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁亥" , "辰", "巳寅亥","元首，元胎，斩关","昼名斩关，干上天罡，闭口突出，大利逃亡");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁亥" , "卯", "未卯亥","涉害，曲直，不备","人得传力，将传废宅，自取其祸，半危半吉");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁亥" , "寅", "午丑申","重审，四绝","交关且尔，妻财废弛，禄既空亡，守之何裨");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁亥" , "丑", "巳亥巳","反吟","改变双双，丁马俱张，论讼难诉，闭口为良");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁亥" , "子", "巳戌卯","重审，铸印，斩关","壬辰及子，支干双水，引从虽远，虎墓宜视");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁亥" , "亥", "未亥卯","重审，曲直，不备，回环","人丰宅隘，后失倚赖，三传皆空，昼将驵侩");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁亥" , "戌", "午戌寅","昴星，斩关，炎上","四虎来咥，宜守术业，火局临木，受用不乏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁亥" , "酉", "酉亥丑","重审，间传，极阴","自用传辰，礼下于人，财为破碎，妻婢伤身");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁亥" , "申", "申酉戌","重审，连茹","三传财喜，人宅化鬼，仔细推详，病死墓矣");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊子" , "巳", "巳申寅","伏吟，元胎","昼虎甲申，夜龙马寅，迤逦克干，闭口无迍");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊子" , "辰", "戌酉申","知一，连茹，斩关","墓神覆日，丁处家庭，发用元武，盗贼后行");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊子" , "卯", "丑亥酉","重审，励德，间传，极阴","彼次遭苦，常防门户，仕宦如逢，荣耀宗祖");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊子" , "寅", "寅亥申","涉害，元胎","身及初传，皆被鬼觇，墓恃申酉，甲乙天干");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊子" , "丑", "巳申丑","昴星，龙战","昼龙遁甲，有贵可压，闭口随时，虎藏槛柙");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊子" , "子", "子未寅","重审，循环，赘婿，不备","循环不已，马载虎鬼，财自天来，进退难矣");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊子" , "亥", "午子午","反吟，高盖","身上财丁，动即虚声，来往空陷，凶吉平平");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊子" , "戌", "巳戌卯","重审，铸印，斩关","传课循环，往赴财乡，干禄尤吉，鬼助生方");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊子" , "酉", "辰申子","元首，润下","夜雀从魁，禽类生财，斗博大获，卜宅兴灾");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊子" , "申", "卯午酉","蒿失，三交","初遥传空，凡占力轻，宅中失耗，休倚贵庭");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊子" , "未", "辰午申","重审，泆女，登三天","自墓传生，递相欺凌，昼虎遁甲，利害交并");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊子" , "午", "寅卯辰","知一，连茹","虚生无益，传逢全克，昼贵伤支，龙合夜贼");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己丑" , "未", "丑戌未","伏吟，自信，稼穑","支传干上，彼求己向，可畏之因，昼夜天将");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己丑" , "午", "子亥戌","重审，退茹，励德","因贵失禄，丁马相逐，文书不利，婚姻急速");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己丑" , "巳", "亥酉未","重审，间传，时遁","宅用马丁，迁移难任，临事闭口，课传五阴");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己丑" , "辰", "子辰戌","昴星，掩目，天烦","叠值魁罡，远涉他乡，贵财发用，无礼须防");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己丑" , "卯", "巳丑酉","涉害，从革，蓦越","传入宅上，俱为脱诳，身既乘鬼，赖此保障");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己丑" , "寅", "卯戌巳","重审，斫轮，四绝，罗网","寅卯两木，灾祸相逐，夜贵入宅，祛殃降福");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己丑" , "丑", "亥未丑","反吟，无亲，淫佚","往来相会，丁马并至，动可取财，守之无利");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己丑" , "子", "巳戌卯","知一，铸印，励德","先冲后击，交后有益，末助初生，如砒在蜜");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己丑" , "亥", "酉丑巳","涉害，从革","丁马载财，传局生来，启齿便得，闭口无灾");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己丑" , "戌", "午戌辰","昴星，二烦，励德","三奇昴星，昼盗兼刑，魁罡并现，动不容停");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己丑" , "酉", "卯巳未","元首，间传，迎阳","败中藏慝，卯木入宅，外勾里连，两贵烦剧。");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己丑" , "申", "寅卯辰","元首，进茹，罗网，正和","三传克日，夜贵临吉，或蒙神佑，利卜官秩");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚寅" , "申", "申寅巳","伏吟，自任，元胎，六仪","禄马随身，两虎并临，居官极品，俗庶灾身");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚寅" , "未", "子亥戌","知一，退茹","夜贵墓身，昼贵墓庭，三传虽水，两丙一丁");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚寅" , "午", "午辰寅","涉害，间传，顾祖，励德","虚忧不实，就生无力，倘聚钱财，祸患尤剧");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚寅" , "巳", "巳寅亥","元首，元胎","干传干支，我就他宜，亥虽解祸，生祸由斯");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚寅" , "辰", "戌午寅","涉害，炎上，斩关，狡童","始课可畏，动用非细，中末既陷，守为上计");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚寅" , "卯", "戌巳子","知一，斫轮，罗网","丙戌丙子，中传逢巳，君子宜占，俗庶有悔");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚寅" , "寅", "寅申寅","反吟，元胎，赘婿","他来我家，我去投他，满目财禄，夜占不佳");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚寅" , "丑", "子巳戌","知一，铸印，蓦越","干支乘墓，昼夜贵遇，二丙遁官，与巳同聚");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚寅" , "子", "辰申子","元首，润下，励德，闭口","人衰宅盛，我羸彼旺，官鬼居家，全不相向");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚寅" , "亥", "申亥寅","重审，元胎，六仪","害变为合，丁马相杂，贵蹉履狱，夜财虎踏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚寅" , "戌", "辰午申","涉害，间传，斩关，登三天","全值魁罡，身动非常，动亦无用，中末空亡");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚寅" , "酉", "辰巳午","重审，进茹，升阶，蓦越","人宅俱旺，动遭罗网，干支坐墓，情怀不爽");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛卯" , "戌", "卯子午","伏吟，龙战，斩关，三交","交合幸美，然后无礼，彼既如兹，我亦若此");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛卯" , "酉", "丑子亥","重审，天狱，励德","禄乘虎元，每被忧煎，墓脱丁扰，不得安然");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛卯" , "申", "亥酉未","涉害，间传","中有旬丁，凶动不宁，昼夜天将，元虎交并");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛卯" , "未", "子未子","昴星，励德，龙战","虎视虎刑，六害重迎，极惊极恐，实脱虚生");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛卯" , "午", "未卯亥","比用，曲直，泆女，寡宿，知一","财化为鬼，足下乘丁，昼如告贵，贿散方成");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛卯" , "巳", "戌巳子","重审，斩关，龙战，不备","人就财所，切宜急取，传课循环，动意难阻");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛卯" , "辰", "卯酉卯","反吟，斫轮，龙战","交互六害，然后和会，两贵不欢，难施恩沛");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛卯" , "卯", "卯申丑","重审，励德，斫轮，赘婿，不备","课传回环，财就人旁，取之宜速，迟归墓乡");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛卯" , "寅", "未亥卯","涉害，龙战，泆女，寡宿","夜贵为财，三传助来，中逢丁亥，取即为灾");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛卯" , "丑", "酉子卯","重审，九丑，励德，天烦","昼虎墓身，夜禄虚惊，中盗末武，昼贵无形");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛卯" , "子", "巳未酉","蒿矢，龙战，泆女，间传，变盈","遥克传空，所作无踪，源涸根断，脱耗无穷");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛卯" , "亥", "辰巳午","重审，斩关，龙战","丁火伤身，病必头痛，递互可恋，昼贵何用");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬辰" , "亥", "亥辰戌","伏吟，杜传，斩关","德禄乘丁，贪财岂宁，中逢墓克，戌虎末迎");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬辰" , "戌", "戌酉申","知一，斩关，魄化","彼己倥偬，他轻我重，中末既生，舍危可用");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬辰" , "酉", "寅子戌","元首，间传","交互和顺，间传拱定，不脱规模，委曲匪径");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬辰" , "申", "巳寅亥","元首，元胎","长生难处，昼夜元虎，闭口之财，丁马动取");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬辰" , "未", "子申辰","重审，励德，狡童","干上无畏，支墓末莅，病困讼刑，行人立至");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬辰" , "午", "午丑申","知一，不备，孤辰","不尊失叙，被下欺侮，夜必亡财，怪临门户");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬辰" , "巳", "巳亥巳","反吟，励德，斩关，闭口","巳及丙丁，总是财星，两贵受克，斩关课名");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬辰" , "辰", "寅未子","重审，不备，乱首","上门欺凌，孟避不能，寅虽可制，渠力难兴");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬辰" , "卯", "未亥卯","重审，寡宿，曲直","夜将皆土，传末救护，常人欲之，君子深恶");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬辰" , "寅", "戌丑辰","遥克，蒿矢，稼穑","互相吞并，夜戌虎盛，身幸乘寅，众鬼钦敬");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬辰" , "丑", "申戌子","重审、六仪、涉三渊","发用长生、丑午来憎、勿依末旺、昼戌虎狞");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬辰" , "子", "丑寅卯","元首，进茹","昼旺乘虎，那堪遁戊，休赖木旺，渠自受苦");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸巳" , "丑", "酉戌未","伏吟，励德，稼穑","五鬼相攻，闭口免凶，昼夜戌虎，病讼重逢");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸巳" , "子", "卯寅丑","元首，退茹，解离","递相克贼，禄被元食，难进难退，课名迫逼");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸巳" , "亥", "丑亥酉","重审，间传，极阴","初鬼末败，丁马独在，千里之行，获财十倍");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸巳" , "戌", "戌未辰","元首，稼穑，闭口","干及三传，凶祸难言，宅中寅木，可敌仇冤");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸巳" , "酉", "巳丑酉","元首，从革","人就财乡，传课循环，昼将土神，忧变怡颜");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸巳" , "申", "卯戌巳","重审，斫轮","交朋合美，财神已矣，生虎鬼龙，一悲一喜");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸巳" , "未", "巳亥巳","反吟，励德","皆马皆丁，不容少停，贵虽难靠，财却丰盈");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸巳" , "午", "午亥辰","重审，斩关，孤辰","夜占被盗，钱财累耗，名值元辰，俱怀凶暴");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸巳" , "巳", "酉丑巳","涉害，从革，不备，赘婿","财来就我，循环相锁，将克传生，众口传播");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸巳" , "辰", "申亥寅","重审，元胎，六仪，斩关","墓克其身，倚赖于寅，不甘之者，初支两申");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸巳" , "卯", "未酉亥","遥克，蒿矢，励德，寡宿，入冥","源消根断，凡谋氾滥，迤逦脱耗，源入幽暗");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸巳" , "寅", "未申酉","遥克，蒿矢，连茹，寡宿","蒿矢空亡，前路嘉祥，寅元午空，失脱先防");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲午" , "寅", "寅巳申","伏吟，自任，元胎","不肯守禄，去临空谷，马载虎鬼，末后相逐");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲午" , "丑", "子亥戌","知一，退茹，三奇","退值生方，进遇空亡，夜逢庚虎，美里成殃");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲午" , "子", "戌申子","涉害，间传，斩关，励德","夜子昼申，总是凶神，六阳数足，革故鼎新");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲午" , "亥", "申巳寅","遥克，蒿矢，元胎","申为矢箭，射中非善，马载马鬼，昼难脱患");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲午" , "戌", "戌午申","重审，炎上，斩关，狡童","人衰宅旺，他忤我向，讼宜顺他，病虚脱丧");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲午" , "酉", "酉辰亥","元首，四绝","元财在中，水生坐空，丁神作鬼，凶动重逢");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲午" , "申", "寅申寅","反吟，无依，涉害，元胎","支干俱伤，又坐克方，舍就不可，彼此匪良");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲午" , "未", "子巳戌","知一，三奇，铸印，引从","交互彼己，两皆不利，夜害贵人，讼遭官制");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲午" , "午", "寅午戌","元首，炎上，励德，泆女","循环脱耗，秋冬急暴，身位频灾，家庭累盗");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲午" , "巳", "申亥寅","知一，元胎","脱空破碎，丁鬼宅内，初马鬼驰，生禄后泰");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲午" , "辰", "辰午申","涉害，间传，斩关，登三天，狡童","空财动取，马载鬼虎，贵坐天门，罡塞鬼户");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲午" , "卯", "辰巳午","重审，进茹，孤辰","支干拱传，空脱双全，孟进不进，耗盗忧煎");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙未" , "辰", "辰未丑","伏吟，自信，斩关，稼穑，游子","三传日辰，总数财神，丑未白虎，大吉乘辛");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙未" , "卯", "戌卯午","昴星，掩目，励德","支上旬首，干上旬尾，首尾纡回，虎视可畏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙未" , "寅", "亥寅巳","昴星，掩目，元胎","元胎衰替，孟临季位，支嗣空亡，长生无气");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙未" , "丑", "丑戌未","重审，稼穑，励德，游子","干就支所，财宜急取，稍缓遭昏，丑辛可惧");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙未" , "子", "卯亥未","元首，曲直，淫泆","贵临乙木，支乘干禄，仔细推之，无礼反目");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙未" , "亥", "午丑申","重审，六仪，四绝","守有生路，解忧散虑，昼贵空亡，夜贵临墓");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙未" , "戌", "戌辰戌","反吟，无依，稼穑，斩关","满目空财，往而不来，宅乘遁鬼，因妻致灾");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙未" , "酉", "巳戌卯","知一，铸印，度厄，励德","丁鸡抱蛇，初中虚花，卯虽是禄，元虎相加");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙未" , "申", "亥卯未","重审，曲直，狡童","自生传墓，先醒后雾，夜贵乘罡，昼贵保护");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙未" , "未", "未戌丑","重审，稼穑，不备，赘婿","辛鬼后墓，休买田土，循环三刑，因财受苦");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙未" , "午", "申戌子","重审，涉三渊，间传","丁鬼入宅，费用不一，尚可交关，贵不见恤");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙未" , "巳", "酉戌亥","遥克，蒿矢，进茹","空脱实鬼，庶俗深畏，仕宦宜占，三奇并值");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙申" , "巳", "巳申寅","伏吟，元胎，励德，寡宿","德空禄亡，中财昼元，末生夜虎，壬遁寅边");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙申" , "辰", "卯寅丑","元首，退茹，斩关","退逢生处，进入空所，事到中门，马载虎鬼");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙申" , "卯", "丑亥酉","重审，逆间，极阴","干上旬尾，支上旬始，干谒贵人，最宜启齿");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙申" , "寅", "巳寅亥","元首，元胎，寡宿，不备","人往就财，传课萦回，所孟未得，所畏须来");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙申" , "丑", "子申辰","重审，润下","事虽难行，亦反可成，惟宜姑待，三六合并");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙申" , "子", "戌巳子","知一，四绝，铸印","彼己无礼，闭口为美，各自昏迷，病绝药饵");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙申" , "亥", "寅申寅","反吟，元胎","递互六害，猜嫌尽在，夜被鬼灾，昼占神怪");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙申" , "戌", "卯申丑","元首，斩关","彼己墓覆，夜贵覆狱，昼病须亡，申入棺木");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙申" , "酉", "酉丑巳","重审，从革","身乘夜贵，昼财破碎，夜将助财，宜乎假贷");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙申" , "申", "申亥寅","重审，元胎，不备，赘婿","长生财贵，夜皆不喜，众口赞扬，无有穷已");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙申" , "未", "子寅辰","重审，斩关，间传，三阳","鬼在墓蹲，招呼病人，夜遁壬虎，勿恃其寅");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙申" , "午", "酉戌亥","遥克，弹射，连茹","身宅旺盛，动变网刃，众贵难凭，死墓绝并");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁酉" , "未", "酉未丑","伏吟，励德，杜传","贵人之财，远方寄来，中末又助，宅内阴灾");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁酉" , "午", "申未午","遥克，弹射，连茹","支传于干，不越模范，昼禄虎临，守之情惨");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁酉" , "巳", "丑巳巳","别责，不备，芜淫","干就支财，破碎空偕，三重如此，虚扰心怀");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁酉" , "辰", "午卯子","元首，轩盖，三交","交加和睦，午神为禄，昼虎夜元，匪美休卜");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁酉" , "卯", "巳丑酉","从革，元首","破碎并空，宅上皆逢，家财已废，将助仍丰");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁酉" , "寅", "亥午丑","重审，斩关","课名斩关，逃者不还，各逢生气，昼贵休干");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁酉" , "丑", "卯酉卯","反吟，无依，龙战，励德","皆贵皆财，皆丁往来，凡谋岂出，行人即回");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁酉" , "子", "未子巳","涉害，度厄","三传内战，事必窝犯，破碎同空，钱财耗散");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁酉" , "亥", "亥卯未","元首，曲直","克身墓宅，两贵受克，昼将窃干，三传制贼");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁酉" , "戌", "子卯午","遥克，蒿矢，斩关，高盖","墓干脱支，身宅虚危，夜占被失，闭口而回");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁酉" , "酉", "酉亥丑","重审，不备，间传，赘婿","身宅皆贵，循环无已，财自然来，末又助起");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁酉" , "申", "亥子丑","知一，进茹，斩关","传归绝墓，商贾勿举，全赖奴仆，免受辛苦");


INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊戌" , "巳", "巳申寅","伏吟，元胎，斩关，孤辰","自初至末，迤逦侵伐，昼勾虎蛇，夜免猖獗");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊戌" , "辰", "卯寅丑","元首，退茹，斩关","退入鬼乡，进向空方，守身昏晦，败坏门墙");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊戌" , "卯", "丑亥酉","重审，励德，极阴","交合可以，彼生我忌，破碎初逢，闭口可畏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊戌" , "寅", "寅亥申","元首，元胎","寅夜青龙，身初两逢，昼申虽制，白虎有凶");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊戌" , "丑", "寅戌午","遥克，蒿矢，炎上","火局生身，夜虎临寅，末并宅上，丑午凶神");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊戌" , "子", "子未寅","重审，不备","我投于彼，两边契义，夜虎临寅，昼占无畏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊戌" , "亥", "巳亥巳","反吟，元胎，无依，斩关，寡宿","我去彼绝，凡占歇灭，病讼皆凶，行人被截");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊戌" , "戌", "申丑午","元首，斩关，不备","昼虎甲午，申类最苦，夜贵当权，初末拱护");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊戌" , "酉", "寅午戌","元首，励德，泆女","寅并甲午，昼夜皆虎，酉金来救，火局焚去");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊戌" , "申", "寅亥巳","遥克，弹射，元胎","长生须弃，财引逢鬼，昼贵入宅，夜为破碎");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊戌" , "未", "子寅辰","重审，间传，泆女，向阳","夜贵身边，两子害焉，罡塞鬼户，昼贵登天");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊戌" , "午", "亥子丑","重审，进茹，三奇","罗身网宅，动则遭厄，财在家中，多贪疲役");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己亥" , "未", "亥未丑","伏吟，自信，杜传","元临财上，贼累相向，虎蛇入未，暗中惆怅");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己亥" , "午", "戌酉申","元首，退茹，斩关，励德","弃禄尤宜，关隔卑微，魁居宅上，百无所依");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己亥" , "巳", "卯丑亥","遥克，蒿矢，间传","六阴俱全，空脱迍邅，破败丁酉，嗣婢熬煎");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己亥" , "辰", "巳寅亥","元首，斩关，励德，寡宿","干上墓神，自末而生，孟脱不脱，宜守家庭");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己亥" , "卯", "未卯亥","涉害，曲直，度厄，不备，乱首","彼己俱乖，弃害就财，循环而已，倘恋灾来");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己亥" , "寅", "午丑申","重审，六仪，四绝","六关和顺，禄神已尽，嗣及长生，占之有吝");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己亥" , "丑", "巳亥巳","反吟，元胎，寡宿","来去皆空，长上须凶，妻妾婢媵、常闹家中");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己亥" , "子", "巳戌卯","知一，铸印，斩关，励德","墓覆家庭，元虎为邻，贵财系子，昼卜临身");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己亥" , "亥", "未亥卯","涉害，曲直，不备，赘婿","财就身宫，恋则为凶，只宜早弃，免被贼通");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己亥" , "戌", "寅巳申","遥克，蒿矢，元胎，励德，斩关","巳类为弓，申象箭容，遗弓落箭，所为无功");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己亥" , "酉", "丑卯巳","涉害，间传，见机，出产","破败临身，况又乘丁，五阴柔日，凡占杳冥");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己亥" , "申", "丑寅卯","元首，进茹，三奇","身宅俱贵，三奇又遇，君子宜之，常人反忌");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚子" , "申", "申寅巳","伏吟，元胎","昼虎临禄，财被马逐，末空破碎，夜病嗣续");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚子" , "未", "戌酉申","元首，连茹","昼虎丙申，禄故难亲，夜宜守贵，初屈后伸");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚子" , "午", "午辰寅","涉害，斩关，间传，六仪，励德，天网","彼己灾殄，寅财休恋，助鬼来攻，缙绅宜见");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚子" , "巳", "午卯子","知一，高盖，六仪","生空破贵，丁刃败气，众祸攻攒，浮财何济");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚子" , "辰", "子申辰","重审，润下，斩关，不备","三传支干，昼夜天将，俱水盗身，难舍难向");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚子" , "卯", "戌巳子","知一，比用","巳火无力，居官被黜，财能救拔，刑子去戌");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚子" , "寅", "寅申寅","反吟，元胎","财中有丙，往来不定，纳粟求官，公用斯正");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚子" , "丑", "巳戌卯","重审，铸印，芜淫，寡宿","交合交克，有凶有吉，仇却和谐，喜有祸出");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚子" , "子", "辰申子","元首，润下，斩关，励德","彼来投己，脱耗无礼，盗贼之徒，不出邑里");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚子" , "亥", "午酉子","遥克，蒿矢，六仪，三交，龙战","蒿矢三交，昼虎难逃，干上及末，少解煎熬");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚子" , "戌", "辰午申","涉害，斩关，登三天，寡宿，间传","四课三传，俱处六阳，昼虎丙申，庶俗难当");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚子" , "酉", "寅卯辰","知一，进茹","马载钱财，身动方来，支干罗网，宅晦人灾");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛丑" , "戌", "丑戌未","伏吟，稼穑，斩关","宅上初传，墓居两边，舍此而动，众力生焉");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛丑" , "酉", "子亥戌","重审，退茹　励德","夜禄难守，遂投贼寇，自身熬煎，他人财厚");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛丑" , "申", "亥酉未","重审，间传，时遁","初马次丁，岂容少停，动因凶事，夜失匪宁");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛丑" , "未", "巳未未","别责，斩关，不备","昼生可托，岂容动作，官德为空，未虎夜恶");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛丑" , "午", "巳丑酉","知一，从革，寡宿，天网","空墓及丁，总是虚名，昼又赖贵，身宅夜迍");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛丑" , "巳", "卯戌巳","重审，斫轮，泆女，铸印","上虽承恩，彼力极轻，巳空卯败，戌墓齐并");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛丑" , "辰", "亥未辰","反吟，斩关，孤辰，井栏射","天罡覆形，足又来并，初为日马，虚动难行");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛丑" , "卯", "卯申丑","重审，励德，芜淫","干乘旬尾，支乘旬始，交互相擒，进退难矣");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛丑" , "寅", "酉丑巳","知一，从革，芜淫，狡童","交相克战，禄丁难恋，天网恢恢，吉凶立见");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛丑" , "丑", "巳丑丑","别责，斩关，寡宿，不备","昼墓虎耽，若此者三，宅堕入晦，守德戒贪");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛丑" , "子", "卯巳未","元首，芜淫","先交后争，上下相刑，笑里含毒，冬夜火惊");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛丑" , "亥", "寅卯辰","元首，进茹","脱气临日，夜元走失，病讼深畏，取财宜疾");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬寅" , "亥", "亥寅巳","伏吟，元胎，励德","交合既有，禄破空守，中末空脱，昼遭贼手");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬寅" , "戌", "子亥戌","知一，退茹，斩关","虎临戊戌，身边并立，同类相扶，其凶再及");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬寅" , "酉", "戌申午","元首，间传，蓦越","先生后败，午财休赖，助起初传，戌虎无奈");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬寅" , "申", "巳寅亥","元首，元胎，不备，寡宿","生被虎攻，往就徒空，舍益就损，终身困穷");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬寅" , "未", "戌午寅","重审、炎上、斩关、励德","财传化鬼，刃蜜休舐，昼虎戊戌，凶灾甚矣");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬寅" , "午", "午辰申","重审，六仪，四绝","因财求利，有妨生计，占长上凶，甘招昏滞");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬寅" , "巳", "寅申寅","反吟，元胎，励德","钱财虚耗，来往逢盗，面前和合、两贵难靠");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬寅" , "辰", "子巳戌","知一，斩关","墓身墓宅，财亡妻失，刃虎昼逢，巳畏子戌");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬寅" , "卯", "未亥卯","重审，曲直","支乘旬始，干乘旬尾，士庶孟之，官宦恶矣");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬寅" , "寅", "申亥寅","重审，元胎，不备，赘婿","彼加我边，末又来兼，虽名三会，无益可占");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬寅" , "丑", "辰午申","重审，斩关，间传，登三天，泆女，寡宿，天网","自墓传生，先迷后醒，卯为年命，两贵相成");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬寅" , "子", "辰巳午","重审，进茹，寡宿","前逢空朽，脱盗在后，彼己无礼，逼迫难守");


INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸卯" , "丑", "丑戌未","伏吟，稼穑，励德","课传八土，癸水受苦，宅中夜贵，可以御侮");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸卯" , "子", "丑子亥","重审、退茹、三奇","夜禄难守，常占殃咎，昼夜天空，勾陈在丑");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸卯" , "亥", "丑亥酉","涉害，极阴，间传，循环","昼将俱土，神愆咒诅，传课循环，灾出无路");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸卯" , "戌", "戌未辰","元首、稼穑、斩关","六合交互，脱难入墓，屑就其禄，渐旺门户");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸卯" , "酉", "未卯亥","涉害，曲直，励德","干上旬丁，引往贼营，夜将皆土，解释冤憎");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸卯" , "申", "卯戌巳","知一，斩关，斫轮，芜淫","交互战伐，不受福德，夜虎临身，脱空鬼贼");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸卯" , "未", "卯酉卯","反吟，励德，龙战","夜贵闭口，宅乘丁酉，动既无财，尤不可守");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸卯" , "午", "午亥辰","重审，六仪","中害末墓，午财勿顾，唯赖申生，夜占虎遇");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸卯" , "巳", "酉丑巳","涉害，从革，绝嗣，孤辰","四课被贼，绝嗣亡族，昼将助传，去祸迎福");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸卯" , "辰", "酉子卯","重审，斩关，三交","禄贵丁财，并墓俱逢，守之昏晦，动则亨通");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸卯" , "卯", "未酉亥","遥克，蒿矢，励德，不备","传及干支，迤逦生上，涸源断根，病讼恶况");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸卯" , "寅", "辰巳午","重审，进茹，龙战，斩关，寡宿","前路皆空，凡事无踪，未免虚动，病讼俱逢");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲辰" , "寅", "寅巳申","伏吟，自任，元胎","德禄俱空，昼虎鬼凶，火命解祸，土命畏逢");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲辰" , "丑", "子亥戌","知一，退茹，重阴","进损退益，戌财必失，冬昼火惊，贵人覆日");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲辰" , "子", "戌申午","涉害，间传，悖戾，闭口，励德","屈尊就财，末午助来，六阳俱备，申虎尤乖");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲辰" , "亥", "申巳寅","蒿矢，元胎","干虽乘亥，切勿自怠，病苏讼宽，其忧尚在");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲辰" , "戌", "戌午寅","涉害，炎上，斩关，狡童","初遭夹克，三传盗日，赖子相制，其象夜吉");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲辰" , "酉", "午丑申","知一，四绝","去煞留官，仕宦欣欢，常人值此，灾祸多端");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲辰" , "申", "寅申寅","反吟，绝胎，孤辰","善者既陷，恶者浪荡，所举百事，无些影响");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲辰" , "未", "寅未子","涉害，度厄，寡宿","干禄告免，家俬内战，传墓入墓，行人立见");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲辰" , "午", "申子辰","蒿矢，润下，励德","笑里有毒，鬼贼满屋，末助初传，午畏水局");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲辰" , "巳", "申亥寅","重审，元胎","宛转益己，不利于彼，家宅动摇，忧变为喜");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲辰" , "辰", "辰午申","涉害，间传，斩关，赘婿，狡童","午火可赖，事不出外，财自然来，昼占可畏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲辰" , "卯", "辰巳午","重审，进茹，六仪，升阶","静则有旺，动遭罗网，昼卜亡财，夜迎盗党");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙巳" , "辰", "辰巳申","伏吟，斩关，六仪","叠遇天罡，身动难康，夜被神挠，幸免残伤");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙巳" , "卯", "卯寅丑","元首，退茹，不备，蓦越","空禄为初，中末仍虚，所谋无效，进步徐徐");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙巳" , "寅", "丑亥酉","重审，间传，极阴，蓦越","四课俱空，万事无踪，昼病不食，夜卜则凶");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙巳" , "丑", "丑戌未","重审，稼穑，游子，闭口","满目财喜，不偿所费，昼虎墓临，闭口无畏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙巳" , "子", "酉巳丑","蒿矢，从革","末助初鬼，尤赖蒿矢，俯丘仰仇，化合为美");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙巳" , "亥", "午丑申","重审，四绝","仕宦畏逢，常人免凶，夜休投贵，昼稍中庸");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙巳" , "戌", "巳亥巳","反吟，无依，元胎","昼虎防脱，亥水难托，夜被欺诈，奸私见约");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙巳" , "酉", "寅未子","重审，寡宿，励德","克身墓宅，昼传夹克，动意难已，凶里财得");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙巳" , "申", "酉丑巳","重审，从革","交合虽逢，鲜克有终，夜占散祸，昼卜屯凶");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙巳" , "未", "未戌丑","知一，稼穑，游子","携钱随鬼，纳粟偏宜，孟求平善，请祷神祇");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙巳" , "午", "申戌子","重审，间传，涉三渊","两贵虽值，俱不可恃，所费百出，住宅移徙");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙巳" , "巳", "未申酉","弹射，进茹，不备，蓦越","泥弹化石，射之有力，止宜守困，前迫后逼");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙午" , "巳", "巳申寅","伏吟，元胎，励德","禄财及生，昼总无成，始如花锦，后若浮萍。");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙午" , "辰", "卯寅丑","元首，退茹，不备","脚踏空亡，休恋生方，向前一步，食禄荣昌");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙午" , "卯", "丑亥酉","重审，退间，极阴","生空变败，与人六害，夜贵惠财，昼贵难赖");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙午" , "寅", "子酉午","蒿矢，三交","四课无形，生如不生，遥克既陷，好恶无成");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙午" , "丑", "戌午寅","重审，炎上，泆女，三奇","自墓传生，遁甲戊庚，得意浓处，掉臂长行");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙午" , "子", "子未寅","知一，四绝","三传内战，昼占灾殄，告贵徒然，交关眷恋");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙午" , "亥", "午子午","反吟，三交","守皆遇鬼，交互不美，壬子居中，仕宦宜矣");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙午" , "戌", "辰酉寅","六仪，斩关，比用","两蛇夹墓，凶灾可恶，干鬼临支，长生木蠹");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙午" , "酉", "酉丑巳","重审，从革，斩关","两贵心灰，夜将助财，禄为破碎，宅惹尘埃");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙午" , "申", "申亥寅","元胎，比用","昼贵鬼魔，夜贵相过，财马入课，荐我者多");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙午" , "未", "申戌子","重审，间传，涉三渊，死奇","支马干丁，客主欢迎，鬼呼病者，动静无成");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙午" , "午", "申酉戌","弹射，进茹，不备","午未禽财，妻妾怀胎，食伤治病，胃腕宜开");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁未" , "未", "未丑戌","伏吟，稼穑","处静而动，奴仆休宠，夜嫁娶费，行人继踵");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁未" , "午", "卯午午","八专，帷簿","四课四虎，受惊受惧，费力千般，未免如故");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁未" , "巳", "丑巳巳","八专，帷簿","破碎遁鬼，四马载起，昼将如逢，传皆陷矣");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁未" , "辰", "亥辰辰","八专，帷簿，斩关","火生四土，夜将白虎，昼贵难靠，宅昏人苦");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁未" , "卯", "亥卯未","元首，曲直","昼将脱干，好恶中半，勿恋传生，宜更宜换");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁未" , "寅", "酉辰亥","比用，孤辰","昼贵临罡，夜贵空方，寅纵生身，熟视不臧");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁未" , "丑", "巳丑丑","反吟，八专，井栏射，励德","丁生四丑，凡占殃咎，四癸暗伤，惟宜闭口");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁未" , "子", "巳戌卯","比用，铸印","克干畏支，狐假虎威，略举动足，踏翻祸机");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁未" , "亥", "亥卯未","重审，曲直，回环","昼将脱日，全赖传力，贵德三传，夜占何益");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁未" , "戌", "亥戌戌","八专，帷簿，斩关","昼墓救应，不幸中幸，反伤夜贵，幸中不幸");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁未" , "酉", "酉亥丑","重审，间传，凝阴","丁死于酉，破碎癸丑，两贵加临，事危闭口");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁未" , "申", "申酉戌","重审，进茹","得财失财，戌月怀胎，伤风肺喘，讼绝复来");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊申" , "巳", "巳申寅","伏吟，元胎","迤逦不利，败也萧何，末助初生，成也萧何");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊申" , "辰", "卯寅丑","元首，退茹，斩关","脚踏空亡，岂容退步，肯舍危疑，青云得路");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊申" , "卯", "丑亥酉","重审，极阴，励德","占身卜宅，总是上克，祸及常流，仕宦宜得");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊申" , "寅", "寅亥申","元胎，比用，不备","尊就卑旁，彼己不臧，两贵俱怒，可脱凶殃");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊申" , "丑", "子申辰","润下，斩关","干乘旬尾，支上旬首，递互暗谋，四季财喜");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊申" , "子", "子未寅","涉害，度厄","巳申为美，以致无礼，涉险登危，全无畏矣");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊申" , "亥", "寅申寅","反吟，元胎","虎鬼空排，切勿贪财，如贪亥水，生起寅来");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊申" , "戌", "卯申丑","元首，斩关","发用虽凶，赖系旬空，如论夜将，三传无踪");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊申" , "酉", "辰申子","元首，润下，励德，六仪","破碎虽遇，钱财满路，彼己乘脱，递互坐墓");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊申" , "申", "寅巳申","蒿矢，元胎，不备","蒿属朽木，逢申委镞，格居三会，两贵履狱");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊申" , "未", "子寅辰","重审，间传，向三阳，泆女","虎载财走，不得人手，用碎己心，笑破人口");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊申" , "午", "戌酉午","昂星，转蓬","元戌加酉，奴偕婢走，既撞网罗，奸逃束手");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己酉" , "未", "酉未丑","伏吟，龙战","静躁不常，失脱须防，动之逢虎，闭口财昌");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己酉" , "午", "戌午申","昴星，励德","昼将辰阴，课传两申，四虎共聚，禄位空存");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己酉" , "巳", "卯丑亥","蒿矢，狡童，不备","破碎乘巳，三传无益，舍此归家，终受疲役");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己酉" , "辰", "午卯子","元首，高盖","禄来生身，交互忻忻，夜传可用，昼将更旬");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己酉" , "卯", "巳丑酉","涉害，从革","身既受克，破碎伤宅，三传全脱，劳心费力");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己酉" , "寅", "亥午丑","蓦越，斩关","初财中禄，不从所孟，闭口临绝，暗财可逐");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己酉" , "丑", "卯酉卯","反吟，龙战","俱空俱鬼，何劳金制，昼将元合，逢私口闭");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己酉" , "子", "未子巳","涉害，绝嗣","课传内战，昼贵相眷，虎随遁鬼，绝嗣尊殄");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己酉" , "亥", "亥卯未","曲直，重审，狡童","利刃置蜜，舐之无益，只宜慷慨，凶灾自释");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己酉" , "戌", "卯午酉","蒿矢，三交，斩关","弓矢斯张，蒿箭何防，那堪堕矢，惊恐无伤");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己酉" , "酉", "丑卯巳","元首，不备，间传，闭口，出产","阴私叠有，独存闭口，昼虎遁鬼，两贵皆丑");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己酉" , "申", "亥子丑","重审，三奇，进茹","进进退退，先忧后喜，讼禁病脾，求财可以");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚戌" , "申", "申寅巳","伏吟，元胎","昼禄虎啮，告贵难说，动陷鬼乡，弄巧成拙");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚戌" , "未", "午巳辰","蒿矢，退茹","未午巳辰，俱火克身，常人深畏，仕宦欣欣");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚戌" , "午", "午辰寅","元首，不备，励德","末助初神，徒为怨憎，居尊礼下，避难逃生");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚戌" , "巳", "巳寅亥","元首，元胎","一毁一誉，全是亥水，朝属长生，暮属干鬼");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚戌" , "辰", "子申辰","重审，润下","昼火丙午，传水可倚，事防再兴，宜绝后虑");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚戌" , "卯", "戌巳子","比用，芜淫","交关致祸，巳不生我，斫朽木轮，三传俱火");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚戌" , "寅", "寅申寅","反吟，元胎，斩关","七虎夜逢，释散灾凶，干乘空绝，身坐绝空");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚戌" , "丑", "申丑午","知一","昆弟及己，占病必死，丙虎昼逢，申在棺里");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚戌" , "子", "辰申子","涉害，润下，励德，六仪","被子息坏，性多懒懈，动坐生方，索还魂债。");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚戌" , "亥", "寅巳申","弹射，元胎，空亡","先失后得，费尽心力，两贵常怒，好恶无迹");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚戌" , "戌", "子寅辰","重审，间传，不备，向阳，赘婿","支戌来生，坐守即亨，稍畏元武，止步休行");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚戌" , "酉", "亥子丑","重审，进茹，三奇","三传脱日，凡谋费力，病危讼刑，嗣婢恼臆");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛亥" , "戌", "亥戌未","伏吟，杜传，斩关","生意特达，投初被脱，丁未凶动，旅情未遏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛亥" , "酉", "戌酉申","元首，斩关，退茹，不备","禄乘元虎，结好不忤，夜奴婢失，相生交互");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛亥" , "申", "午辰寅","元首，间传，顾祖","未虽助初，赖此旬无，徒取怨憎，权称虚拘");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛亥" , "未", "巳寅亥","元首，元胎，蓦越，励德","初马丁杂，投虎空脱，君子犹迍，常流怎活");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛亥" , "午", "未卯亥","涉害，曲直，度厄","宅并身灾，鬼掠钱财，携金告贵，此其宜哉");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛亥" , "巳", "午丑申","重审，四绝","采葛寻脑，幽隐难考，夜元克身，丙午又造");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛亥" , "辰", "巳亥巳","反吟，元胎，斩关","两贵受克，生值绝域，浊气所生，失十得一");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛亥" , "卯", "卯申丑","重审，励德，孤辰","来情占失，夜贵无力，斫朽木轮，所谋阴慝");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛亥" , "寅", "未亥卯","知一，曲直","夜虎丁火，勿恃传课，交合何益，无财有祸");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛亥" , "丑", "巳申亥","蒿矢，元胎，励德","马上张弓，矢箭申空，幸脱孤矢，虎墓须逢");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛亥" , "子", "丑卯巳","涉害，间传，泆女，出户，闭口","财德既空，墓虎独存，病绝药食，恐丧其魂");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛亥" , "亥", "丑寅卯","元首，进茹，不备，闭口","故意相亏，狐假虎威，己财既失，意外何希");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬子" , "亥", "亥子卯","伏吟，励德，三奇，杜传","德禄幸临，贪心再成，孟其兴旺，无礼遭刑");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬子" , "戌", "戌酉申","退茹，斩关，不备，元首","先疑后遂，佯输诈退，病讼逢斯，昼夜皆晦");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬子" , "酉", "戌申午","元首，斩关，间传","宅上为初，昼占难居，叵耐末午，助鬼趑趄");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬子" , "申", "午卯子","比用，三交，高盖","夜遁戊虎，财亡妻苦，中末皆空，败坏门户");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬子" , "未", "未卯亥","涉害，曲直，励德","丁鬼临身，暗戊加辰，财如刃蜜，夜卜为迍");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬子" , "午", "午丑申","重审，四绝，泆女","夜申遁鬼，长生无气，或卜财亡，或缘妻婢");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬子" , "巳", "午子午","反吟，励德","两贵无力，博奕大获，满目钱财，身心疲役");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬子" , "辰", "巳戌卯","重审，铸印，斩关","两贵引从，再复旧俸，久处沉滞，忽然擢用");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬子" , "卯", "未亥卯","重审，曲直，斩关","夜将难受，木局为救，昼卜俱空，占官虚谬");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬子" , "寅", "午酉子","弹射，三交","课无涯岸，执弓妄弹，末刃虎元，凶存吉散");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬子" , "丑", "辰午申","重审，励德，间传，六仪，泆女，登三天","自墓传生，交合相并，劣猿难靠，羸马难乘");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬子" , "子", "寅卯辰","知一，进茹，不备","支神作旺，来临干上，倘孟改谋，迭遭欺诳");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸丑" , "丑", "丑戌未","伏吟，乱首，励德，游子，稼穑","见财动心，凶祸来侵，中传虎鬼，仕宦宜临");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸丑" , "子", "子亥戌","重审，退茹","旺禄可用，子丑合共，牛女婚宜，公讼动众");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸丑" , "亥", "亥酉未","重审，三奇，时遁","行人出外，携财而至，未与巳酉，难为亥类");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸丑" , "戌", "戌未辰","元首，稼穑，游子，斩关","谋财祸攻，昼将弥凶，宜占官职，喜事重逢");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸丑" , "酉", "巳酉丑","元首，从革，励德","将克传生，己酉败人，宅衰人盛，惟便缙绅");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸丑" , "申", "卯戌巳","重审，斫轮，四绝","没溺财爻，朽木难雕，两贵常怒，守旧逍遥");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸丑" , "未", "未丑未","反吟，稼穑，励德，游子","四丁临未，刃蜜难舐，贵人休干，美中不美");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸丑" , "午", "未卯亥","重审","午系财类，来往受制，妻病财亡，难就难弃");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸丑" , "巳", "酉丑巳","涉害，从革","人盛宅狭，彼恶己益，众语来生，官应显赫");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸丑" , "辰", "辰未戌","重审，铸印，斩关","鬼贼纷纷，凶不可闻，纵寅卯命，亦作妖氛");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸丑" , "卯", "卯巳未","元首，不备，间传，励德，迎阳","拟贵告贵，事致委靡，现在财亡，遁丁何济");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸丑" , "寅", "寅卯辰","元首，进茹，孤辰","干支及传，脱空满前，子息耗盗，弱病淹延");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲寅" , "寅", "寅巳申","伏吟，自任，元胎","德禄临身，夜贵有成，马载虎鬼，动用相刑");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲寅" , "丑", "子亥戌","知一，退茹，孤辰","亥子空亡，戊又来伤，凡谋不利，病讼难当");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲寅" , "子", "戌申午","元首，间传，悖戾，闭口，励德","两水空润，虎鬼作衅，水上人言，不足取信");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲寅" , "亥", "丑亥亥","八专，寡宿，闭口","幸有生涯，贵许空财，纡回宛转，仍旧归来");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲寅" , "戌", "戌午寅","重审，炎上，斩关，狡童","三传全盗，有财虚耗，夜贵登天，神祇宜告");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲寅" , "酉", "酉辰亥","八专，元首，四绝","破碎伤人，又损宅庭，夏夜防火，病讼俱兴");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲寅" , "申", "寅申寅","反吟，元胎，六仪","彼此伤残，马载鬼官，德禄乘虎，灾祸多端");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲寅" , "未", "子巳戌","知一，度厄，铸印，孤辰","干支乘墓，空败无据，嗣息动灾，讼庭贵怒");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲寅" , "午", "申午午","八专，帷簿，励德","昼虎四排，却祸生灾，求官成事，卒难称怀");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲寅" , "巳", "申亥寅","重审，元胎","丁马交并，岂容少停，提防失脱，病赴幽冥");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲寅" , "辰", "辰午申","重审，间传，登三天，斩关","昼占可怖，马载鬼虎，贵登天门，罡塞鬼户");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("甲寅" , "卯", "辰巳午","重审，进茹，升阶","前脱后亡，守之为强，贪一粒粟，失半年粮");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙卯" , "辰", "辰卯子","伏吟，斩关，杜传","彼此猜忌，渐变无礼，昼贵徒然，干禄得体");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙卯" , "卯", "丑子亥","重审，退茹，三奇","坐守我旺，进则无况，踏脚空亡，岂宜前向");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙卯" , "寅", "亥酉未","涉害，间传，极阴，九丑","财生俱空，辛酉独逢，所恶满目，所孟无踪");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙卯" , "丑", "丑戌未","重审，稼穑，励德","两蛇空布，财归鬼墓，外合无凭，内害可惧");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙卯" , "子", "未卯亥","元首，曲直，泆女","禄神墓神，皆与虎并，空贵生干，自墓传生");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙卯" , "亥", "午丑申","涉害，四绝","昼传皆空，夜贵无踪。占官不利，远祸有功");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙卯" , "戌", "卯酉卯","反吟，无依，龙战，三交","交互反吟，卯虎酉螣　夜占夏令，火烛惊心");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙卯" , "酉", "寅未子","重审，六仪，励德","干上至末，迤逦征伐，祸里生财，互相触突");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙卯" , "申", "未亥卯","涉害，曲直","夜贵克身，昼贵虚陈，支禄恼怀，家人悔迍");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙卯" , "未", "酉子卯","涉害，三交，励德","面善含毒，常招耻辱，灾不成灾，福不成福");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙卯" , "午", "申戌子","重审，间传，涉三渊","两贵无力，所求难得，家有惊危，丁马入宅");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("乙卯" , "巳", "辰巳午","重审，进茹，斩关，乱首","丁与马共，动则费用，末助初财，屈尊求俸");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙辰" , "巳", "巳申寅","伏吟，斩关，元胎，励德","禄财长生，空虎纵横，静中须动，所作无成");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙辰" , "辰", "卯寅丑","伏吟，退茹，斩关，不备","还嗣息债，长生宁耐，然后散忧，退空无害");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙辰" , "卯", "丑亥酉","重审，寡宿，间传，极阴","两相交会，各有利害，昼夜贵加，亥水休赖");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙辰" , "寅", "亥申巳","遥克，蒿矢，元胎，三奇","破碎临庭，耗散财婚，昼占告贵，不语沉吟");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙辰" , "丑", "子申辰","重审，润下，励德，寡宿","课传没溺，凶灾可释，外勾里连，夜多淫泆");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙辰" , "子", "午丑申","知一，四绝","中末虚无，独用午初，动逢羊刃，昼贵归庐");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙辰" , "亥", "巳亥巳","反吟，斩关，励德，元胎","满地皆丁，动遇贵成，夜占不动，鬼墓难兴");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙辰" , "戌", "寅未子","重审，斩关，六仪","妻财虽美，恋之害己，众口一词，乘马遭耻");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙辰" , "酉", "酉丑巳","重审，从革","交关利己，昼贵莫倚，夜将助才，金多生水");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙辰" , "申", "申亥寅","重审，元胎","财贵长生，传内俱陈，迤逦相荐，夜变成迍");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙辰" , "未", "申戌子","重审，励德，间传，涉三渊，天狱","初财末官，仕宦忻欢，壬戌干覆，元子偷瞒");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丙辰" , "午", "亥午午","别责，三奇，不备","贵及旺龙，昼占即逢，鬼贼羊刃，夜卜须凶");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁巳" , "未", "巳申寅","伏吟，元胎，励德","支干拱禄，元财捧逐，夜虎临寅，双丁动速");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁巳" , "午", "卯寅丑","元首，退茹，斩关","旺禄长生，昼夜虎并，身心费尽，略无少成");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁巳" , "巳", "丑亥酉","重审，不备，间传，极阴，寡宿，赘婿","丁马俱现，人宅相恋，亥水全亏，两贵相见");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁巳" , "辰", "亥申巳","遥克，蒿矢，元胎，闭口","昼真斩关，逃者不还，马射孤矢，委镞伤残");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁巳" , "卯", "亥卯未","遥克，蒿矢，曲直，励德","将脱传生，蒿矢惊人，末至初位，迤逦伤身");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁巳" , "寅", "酉辰亥","涉害，度厄，四绝","夜贵坏寅，亥力极轻，秋昼火厄，三传自刑");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁巳" , "丑", "巳亥巳","反吟，元胎，励德","脱空宜弃，丁马迭至，夜动文书，昼动因贵");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁巳" , "子", "巳戌卯","重审，铸印，斩关","空鬼加身，实墓临庭，孟动不动，守则虚惊");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁巳" , "亥", "酉丑巳","重审，从革","两贵共排，夜将助财，贪财不足，生鬼为灾");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁巳" , "戌", "申亥寅","重审，元胎，斩关","舍去疑虑，其财可取，因此求生，宜文宜武");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁巳" , "酉", "酉亥丑","重审，励德，不备，间传","夜贵多嗔、破败财婚、昼贵闭口、力弱言轻");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("丁巳" , "申", "申酉戌","重审，进茹","交车和顺，求财急进，病讼因贪，昼贵休近");


INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊午" , "巳", "巳申寅","伏吟，元胎","末助初生，迤逦相侵，初丁中马，佛口蛇心");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊午" , "辰", "卯寅丑","元首，退茹，不备，斩关","昏晦其身，宅镇丁神，鬼居墓上，招呼病人");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊午" , "卯", "丑亥酉","重审，斩关，间传，励德，寡宿","伤身墓宅，用传空域，末逢脱败，略无少益");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊午" , "寅", "寅亥申","元首，元胎，六仪","见处危险，中末求援，迤逦生寅，因财致谴");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊午" , "丑", "戌午寅","重审，炎上，狡童，九丑","传火生身，夜占畏寅，修身谨行，美里生嗔");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊午" , "子", "子未寅","重审，九丑，四绝","四课无形，事迹难明，夜虎居末，木力犹轻");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊午" , "亥", "午子午","反吟，三交","来往皆空，凡事无踪，喜不为喜，凶不为凶");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊午" , "戌", "辰酉寅","知一，幼度厄，斩关","传墓脱鬼，可畏不美，端坐家中，坐食陪费");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊午" , "酉", "寅午戌","元首，六仪，炎上，斩关，励德，狡童","夜虎临寅，可畏灾迍，酉不能制，传局火神");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊午" , "申", "酉子卯","重审，三交","贵坐魁罡，中末空亡，独存初酉，脱败非常");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊午" , "未", "申戌子","重审，涉三渊，间传","往来交媾，长生可就，唯忌取财，苗而不秀");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("戊午" , "午", "寅午午","别责，不备，六仪","彼来生己，守之如意，倘若动谋，鬼刃俱值");


INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己未" , "未", "未丑戌","伏吟，稼穑","支干相逢，中末刑空，无异独足，昼虎三重");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己未" , "午", "卯午午","八专，帷簿","从军食禄，方才享福，惟忌昼空，占病必哭");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己未" , "巳", "丑巳巳","八专，帷簿，孤辰","破碎作空，费耗贫穷，丁马遍布。一世飘蓬");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己未" , "辰", "亥辰辰","八专，斩关，励德","财神闭口，不得人手，四墓乘勾，昏迷难受");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己未" , "卯", "卯亥未","元首，曲直，狡童","虎乙夜占，木局为传，常人仕宦，总受迍邅");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己未" , "寅", "酉辰亥","知一，四绝，无禄","鬼宿鬼门，卦号离魂，酉金勿恃，生祸之根");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己未" , "丑", "巳丑丑","反吟，井栏射，八专，无亲","初值丁马，动意难舍，守空撞空，渐为贫者");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己未" , "子", "巳戌卯","知一，铸印，励德","财既双空，丁马虚逢，卯鬼宜助，凶祸难容");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己未" , "亥", "亥卯未","重审，曲直，三奇，狡童","三木并立，合成曲直，取则为灾，不取可惜");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己未" , "戌", "亥戌戌","八专，斩关，励德","一位财星，四戌来争，争之不已，致讼遭刑");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己未" , "酉", "酉酉酉","八专，独足","此系独足，脱欺叠逐，舟车宜驾，婢逃归屋");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("己未" , "申", "未申申","八专，帷簿","申类子孙，却是长生，慈鸟反哺，夜贵尤荣");


INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚申" , "申", "申寅巳","伏吟，元胎","昼逢四虎，动无少阻，丁马入传，行人商旅");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚申" , "未", "酉未未","八专","初遭网罗，障难无挪，秋冬事贵，得助极多");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚申" , "午", "午辰寅","元首，励德，间传，顾祖","若取寅财，生起祸来，财官绶印，君子宜哉");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚申" , "巳", "巳寅亥","元首，元胎","夜克昼生，丁马俱迎，末之亥水，能败能成");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚申" , "辰", "子申辰","重审，润下，斩关","盗气传逢，初中幸空，独有辰土，生气无穷");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚申" , "卯", "戌巳子","知一，龙战","丁鬼中遇，子戌可拒，却祸除殃，卯财任取");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚申" , "寅", "寅申寅","反吟，元胎，六仪","四财一禄，夜虎趋逐，四马并进，奔驰反覆");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚申" , "丑", "卯丑丑","八专，帷簿","四员昼贵，全然无气，纵有浮财，夜占可畏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚申" , "子", "辰申子","元首，润下，励德","脱空满前，水作三传，昼夜水将，耗盗缠绵");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚申" , "亥", "丑亥亥","八专，帷簿，寡宿","凡事缄默，可脱灾厄，事关贵人，甘受岑寂");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚申" , "戌", "子寅辰","重审，斩关，间传，向三阳，泆女","戌覆宅身，驿马虚寅，动被虎盗，末逢丙辰");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("庚申" , "酉", "亥酉酉","八专，帷簿，三奇","守旺则昌，动则有伤，两酉为刃，灾害非常");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛酉" , "戌", "酉戌未","伏吟，斩关，龙战","旺禄临支，元虎相随，前逢生意，争斗无时");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛酉" , "酉", "丑酉酉","别责，励德，不备","旺禄难恃，元虎交值，重叠恼怀，皆因奴婢");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛酉" , "申", "午辰寅","元首，间传，顾祖","切勿取财，取则灾来，费钱告贵，此卜宜哉");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛酉" , "未", "午卯子","元首，高盖，励德，三交","未土乘虎，再逢二午，孟求成功，略无少补");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛酉" , "午", "巳丑酉","知一，从革","彼己遭伤，交互尤殃，鬼丁破碎，宅怪难当");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛酉" , "巳", "亥午丑","重审，三奇，斩关，四绝","丁马天罡，动意非常，鬼败空墓，官庶皆殃");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛酉" , "辰", "卯酉卯","反吟，龙战，斩关，斫轮","上下六害，交互无碍，门户奸私，元合在内");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛酉" , "卯", "未子巳","知一，度厄，励德","财虽满前，取为祸端，身不安逸，众语攻攒");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛酉" , "寅", "寅午戌","重审，炎上，六仪","传官将生，仕宦兴荣，常人释虑，阴私贵成");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛酉" , "丑", "卯午酉","遥克，弹射，励德，三交，寡宿","四课传初，表里皆虚，妻财尽失，见合如无");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛酉" , "子", "丑卯巳","元首，寡宿，泆女","自墓传生，末鬼乘丁，昼财须失，凶动难停");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("辛酉" , "亥", "亥子丑","重审，进茹，斩关，三奇，不备","重脱墓空，凶吉无踪，尊就卑幼，旺禄才逢");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬戌" , "亥", "寅戌未","伏吟，斩关，励德，三奇","干与初传，闭口难言，两戌一未，勾虎为冤");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬戌" , "戌", "戌酉申","元首，退茹，斩关，乱首，不备","支戌为卑，上门相欺，唯宜猛弃，长生后随");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬戌" , "酉", "午辰寅","元首，泆女，励德，顾祖","末传是寅，喻伐柯人，助其妻类，大利婚姻");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬戌" , "申", "巳寅亥","元首，元胎","夜常临宅，喜中不测，省亲致病，惹鬼为慝");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬戌" , "未", "未卯亥","涉害，曲直，励德","夜失金钱，将士为冤，休言传盗，救祸之源");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬戌" , "午", "午丑申","重审，四绝，泆女","妻奴作怪，子息讨债，迤逦生身，财因此坏");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬戌" , "巳", "巳亥巳","反吟，元胎，励德，斩关","财内藏丁，役损身心，家人丑恶，病讼频临");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬戌" , "辰", "辰酉寅","涉害，斩关","彼己受伐，传墓败脱，宅上引从，家道广阔");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬戌" , "卯", "未亥卯","重审，曲直","递互可亲，夜将克身，三传脱气，却为救神");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬戌" , "寅", "辰未戌","遥克，蒿矢，稼穑，励德，芜淫","蒿矢虚惊，交互欺凌，身依寅木，众鬼难侵");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬戌" , "丑", "子寅辰","重审，励德，间传，向三阳","四课初中，总是旬空，独存末克，鬼户纵横");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("壬戌" , "子", "亥子丑","重审，进茹，乱首，不备，三奇","不尊其身，就卑克治，昼将天空，三传俱弃");

INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸亥" , "丑", "丑戌未","伏吟，稼穑，励德","略得便宜，如若再为，人神共怒，刑废双随");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸亥" , "子", "戌酉申","元首，退茹，斩关","幸乘旺禄，弃寻虎厄，投末之生，失万得百");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸亥" , "亥", "未巳卯","遥克，蒿矢，间传，不备","破败临宅，初鬼遥克，两贵扶同，亡财始获");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸亥" , "戌", "巳寅亥","元胎，斩关","鬼龙生虎，怒喜喜怒，昼贵升擢，丁马之故");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸亥" , "酉", "未卯亥","涉害，曲直，度厄，励德","破败临身，己未克辰，占逢夜将，官悦俗忻");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸亥" , "申", "卯戌巳","知一，斫轮，四绝，铸印","元虎为生，两贵无心，丁马全弱，昼戌难任");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸亥" , "未", "巳亥巳","反吟，元胎，励德","三马三丁，动止频频，贵情未足，宅徙人迍");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸亥" , "午", "午亥辰","重审，斩关","四课之内，辰午酉亥，两贵为邻，家宅昏昧");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸亥" , "巳", "酉丑巳","涉害，从革，度厄","丁马临日，两贵辅弼，因财速动，将凶传吉");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸亥" , "辰", "辰未戌","元首，稼穑，斩关","墓克其身，三传共嗔，颠危可解，全赖家人");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸亥" , "卯", "丑卯巳","涉害，不备，间传，励德，出户","昼夜贵聚，财马共处，助起空亡，循环灾苦");
INSERT INTO Refer(row_id,col_id,refer,ke_ti,ke_yi) VALUES ("癸亥" , "寅", "丑寅卯","元首，进茹，空亡","交互和谐，惟宜脱灾，昼常牛女，婚遇良媒");


SELECT * FROM Refer
